"""Add full_name and department fields to User

Revision ID: 035f76fdbbb9
Revises: 0ee56191c71f
Create Date: 2026-09-20 10:31:32.328890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '035f76fdbbb9'
down_revision: Union[str, Sequence[str], None] = '0ee56191c71f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('department_code', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('department_name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('designation', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'designation')
    op.drop_column('users', 'department_name')
    op.drop_column('users', 'department_code')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###
