"""Added valid_from valid_to schemas

Revision ID: 08d8146c3229
Revises: 6b65930e27e5
Create Date: 2026-09-25 20:33:21.344413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '08d8146c3229'
down_revision: Union[str, Sequence[str], None] = '6b65930e27e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certificate_records',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=True),
    sa.Column('sci_score', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiry_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('file_path_or_blob', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_certificate_records_id'), 'certificate_records', ['id'], unique=False)
    op.create_index(op.f('ix_certificate_records_session_id'), 'certificate_records', ['session_id'], unique=False)
    op.create_index(op.f('ix_certificate_records_user_id'), 'certificate_records', ['user_id'], unique=False)
    op.add_column('assessments', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessments', sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True))
    op.add_column('assessments', sa.Column('reveal_score_to_user', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('assessments', sa.Column('role_template_used', sa.String(length=255), nullable=True))
    op.add_column('question_bank', sa.Column('question_type', sa.String(length=32), server_default='MCQ', nullable=False))
    op.add_column('question_bank', sa.Column('correct_answer', sa.Text(), nullable=True))
    op.add_column('question_bank', sa.Column('grounding_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('question_bank', sa.Column('reviewer_notes', sa.Text(), nullable=True))
    op.alter_column('question_bank', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('question_bank', 'correct_option_index',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('question_bank', 'correct_option_index',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('question_bank', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('question_bank', 'reviewer_notes')
    op.drop_column('question_bank', 'grounding_verified')
    op.drop_column('question_bank', 'correct_answer')
    op.drop_column('question_bank', 'question_type')
    op.drop_column('assessments', 'role_template_used')
    op.drop_column('assessments', 'reveal_score_to_user')
    op.drop_column('assessments', 'valid_to')
    op.drop_column('assessments', 'valid_from')
    op.drop_index(op.f('ix_certificate_records_user_id'), table_name='certificate_records')
    op.drop_index(op.f('ix_certificate_records_session_id'), table_name='certificate_records')
    op.drop_index(op.f('ix_certificate_records_id'), table_name='certificate_records')
    op.drop_table('certificate_records')
    # ### end Alembic commands ###
