"""add file_path to manual

Revision ID: 13daba3ec390
Revises: 9cbb42cf750e
Create Date: 2026-09-22 09:37:44.732397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13daba3ec390'
down_revision: Union[str, Sequence[str], None] = '9cbb42cf750e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manuals', sa.Column('file_path', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('manuals', 'file_path')
    # ### end Alembic commands ###
