"""Add face_embedding to users

Revision ID: 24d44c4139f1
Revises: 34263e67ce9c
Create Date: 2026-09-29 13:31:30.533953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '24d44c4139f1'
down_revision: Union[str, Sequence[str], None] = '34263e67ce9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('integrity_score', sa.Float(), nullable=True))
    op.add_column('exam_sessions', sa.Column('warning_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('exam_sessions', sa.Column('anomaly_clips', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('question_bank', sa.Column('correct_option_indices', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('face_embedding', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'face_embedding')
    op.drop_column('question_bank', 'correct_option_indices')
    op.drop_column('exam_sessions', 'anomaly_clips')
    op.drop_column('exam_sessions', 'warning_count')
    op.drop_column('exam_sessions', 'integrity_score')
    # ### end Alembic commands ###
