"""add sequence_number to user

Revision ID: 2bf9ca1bc5a7
Revises: 035f76fdbbb9
Create Date: 2026-09-20 19:22:59.195021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf9ca1bc5a7'
down_revision: Union[str, Sequence[str], None] = '035f76fdbbb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sequence_number', sa.Integer(), nullable=True))
    op.create_unique_constraint('uix_company_dept_seq', 'users', ['company_id', 'department_code', 'sequence_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_company_dept_seq', 'users', type_='unique')
    op.drop_column('users', 'sequence_number')
    # ### end Alembic commands ###
