"""add_lockdown_fields_to_exam_sessions

Revision ID: 34263e67ce9c
Revises: 9cb4995e1747
Create Date: 2026-09-29 11:19:19.277749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '34263e67ce9c'
down_revision: Union[str, Sequence[str], None] = '9cb4995e1747'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('exam_key_hash', sa.String(length=128), nullable=True))
    op.add_column('exam_sessions', sa.Column('lockdown_anomalies', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.add_column('exam_sessions', sa.Column('lockdown_escalated', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'lockdown_escalated')
    op.drop_column('exam_sessions', 'lockdown_anomalies')
    op.drop_column('exam_sessions', 'exam_key_hash')
    # ### end Alembic commands ###
