"""Add duration_mins to Assessment

Revision ID: 4a4a4be50f2e
Revises: 3b28f987a7be
Create Date: 2026-10-01 13:12:31.038374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a4a4be50f2e'
down_revision: Union[str, Sequence[str], None] = '3b28f987a7be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assessments', sa.Column('duration_mins', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessments', 'duration_mins')
    # ### end Alembic commands ###
