"""Add reference_images to Rule

Revision ID: 6b65930e27e5
Revises: 165ce1e51da6
Create Date: 2026-09-24 09:47:47.604384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b65930e27e5'
down_revision: Union[str, Sequence[str], None] = '165ce1e51da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('reference_images', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'reference_images')
    # ### end Alembic commands ###
