"""add_difficulty_blank_variants_usage_history_marking

Revision ID: 9cb4995e1747
Revises: 08d8146c3229
Create Date: 2026-09-29 11:10:05.625327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cb4995e1747'
down_revision: Union[str, Sequence[str], None] = '08d8146c3229'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_usage_history',
    sa.Column('employee_id', sa.Uuid(), nullable=False),
    sa.Column('question_variant_id', sa.Uuid(), nullable=False),
    sa.Column('exam_session_id', sa.Uuid(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_variant_id'], ['question_bank.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_usage_history_employee_id'), 'question_usage_history', ['employee_id'], unique=False)
    op.create_index(op.f('ix_question_usage_history_exam_session_id'), 'question_usage_history', ['exam_session_id'], unique=False)
    op.create_index(op.f('ix_question_usage_history_id'), 'question_usage_history', ['id'], unique=False)
    op.create_index(op.f('ix_question_usage_history_question_variant_id'), 'question_usage_history', ['question_variant_id'], unique=False)
    op.create_index('ix_quh_employee_variant', 'question_usage_history', ['employee_id', 'question_variant_id'], unique=False)
    # Add new assessment marking columns with server defaults (existing rows get the default)
    op.add_column('assessments', sa.Column('marks_per_question', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('assessments', sa.Column('use_weighted_marks', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('assessments', sa.Column('pass_mark_pct', sa.Float(), nullable=False, server_default='80.0'))
    op.add_column('assessments', sa.Column('pass_mark_abs', sa.Integer(), nullable=True))
    # Remove server defaults after backfill (column now application-managed)
    op.alter_column('assessments', 'marks_per_question', server_default=None)
    op.alter_column('assessments', 'use_weighted_marks', server_default=None)
    op.alter_column('assessments', 'pass_mark_pct', server_default=None)
    op.add_column('question_bank', sa.Column('blank_answer_variants', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('question_bank', sa.Column('difficulty', sa.String(length=16), nullable=False, server_default='medium'))
    op.alter_column('question_bank', 'difficulty', server_default=None)
    op.drop_column('users', 'plain_password')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('plain_password', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('question_bank', 'difficulty')
    op.drop_column('question_bank', 'blank_answer_variants')
    op.drop_column('assessments', 'pass_mark_abs')
    op.drop_column('assessments', 'pass_mark_pct')
    op.drop_column('assessments', 'use_weighted_marks')
    op.drop_column('assessments', 'marks_per_question')
    op.drop_index('ix_quh_employee_variant', table_name='question_usage_history')
    op.drop_index(op.f('ix_question_usage_history_question_variant_id'), table_name='question_usage_history')
    op.drop_index(op.f('ix_question_usage_history_id'), table_name='question_usage_history')
    op.drop_index(op.f('ix_question_usage_history_exam_session_id'), table_name='question_usage_history')
    op.drop_index(op.f('ix_question_usage_history_employee_id'), table_name='question_usage_history')
    op.drop_table('question_usage_history')
    # ### end Alembic commands ###
