"""update question bank schema

Revision ID: 9cbb42cf750e
Revises: 2bf9ca1bc5a7
Create Date: 2026-09-22 09:28:03.714455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9cbb42cf750e'
down_revision: Union[str, Sequence[str], None] = '2bf9ca1bc5a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('question_text', sa.Text(), nullable=False))
    op.add_column('question_bank', sa.Column('correct_option_index', sa.Integer(), nullable=False))
    op.add_column('question_bank', sa.Column('confidence', sa.Float(), nullable=False))
    op.add_column('question_bank', sa.Column('review_status', sa.String(length=32), nullable=False))
    op.drop_index(op.f('ix_question_bank_status'), table_name='question_bank')
    op.drop_column('question_bank', 'stem')
    op.drop_column('question_bank', 'reviewer_notes')
    op.drop_column('question_bank', 'grounding_verified')
    op.drop_column('question_bank', 'status')
    op.drop_column('question_bank', 'explanation')
    op.drop_column('question_bank', 'correct_answer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question_bank', sa.Column('correct_answer', sa.VARCHAR(length=8), autoincrement=False, nullable=False))
    op.add_column('question_bank', sa.Column('explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('question_bank', sa.Column('status', postgresql.ENUM('DRAFT', 'APPROVED', 'REJECTED', name='questionstatus_enum'), autoincrement=False, nullable=False))
    op.add_column('question_bank', sa.Column('grounding_verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('question_bank', sa.Column('reviewer_notes', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('question_bank', sa.Column('stem', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_question_bank_status'), 'question_bank', ['status'], unique=False)
    op.drop_column('question_bank', 'review_status')
    op.drop_column('question_bank', 'confidence')
    op.drop_column('question_bank', 'correct_option_index')
    op.drop_column('question_bank', 'question_text')
    # ### end Alembic commands ###
